
# abort if no config is set
if len(config) == 0:

    raise ValueError('config not set, make sure to run snakemake with config file')

snakemake_dir = sys.path[0]
output_dir = config['output_dir']
conda_env_dir = snakemake_dir + '/envs'
log_dir = output_dir + '/logs'
#target_files = [output_dir + '/' + outfile for outfile in config['target_files']]
temp_dir = config['temp_dir']

### SRAscraper v0.1.0 NCBI SRA Fastq Sequencing File Downloader

### COLLECT METADATA

#rule all:
#    input:
#    target_files

rule find_metadata:
    output:
        first  = output_dir +'/dictionary_file.txt'
    params:
        NCBI_search_txt = config['NCBI_search_txt'],
        computing_threads = config['computing_threads'],
        output_dir = config['output_dir']
    log:
        log_dir + '/find_metadata.log'
    priority: 2
    conda:
        conda_env_dir + '/metadata.yaml'
    script:
        'scripts/metadata.py'

rule download_files:
    params:
        computing_threads = config['computing_threads'],
        output_dir = config['output_dir']
    log:
        log_dir + 'fastq_download.log'
    priority: 1
    conda:
        conda_env_dir + '/fastq_download.yaml' 
    script:
        'scripts/fastq_download.py'

