
# abort if no config is set
if len(config) == 0:

    raise ValueError('config not set, make sure to run snakemake with config file')

snakemake_dir = sys.path[0]
output_dir = config['output_dir']
metadata_dir = output_dir + '/metadata'
qc_dir = output_dir + '/QC'
conda_env_dir = snakemake_dir + '/envs'
log_dir = output_dir + '/logs'
temp_dir = config['temp_dir']

### SRAscraper v0.1.0 NCBI SRA Fastq Sequencing File Downloader

### COLLECT METADATA

rule all:
    input:
        qc_dir + '/multiqc_report.html'

rule find_metadata:
    output:
        first  = metadata_dir + '/dictionary_file.pkl'
    params:
        NCBI_search_txt = config['NCBI_search_txt'],
        computing_threads = config['computing_threads'],
        output_dir = config['output_dir']
    log:
        log_dir + '/find_metadata.log'
    conda:
        conda_env_dir + '/metadata.yaml'
    script:
        'scripts/metadata.py'

rule download_and_qc_files:
    input:
        first = metadata_dir + '/dictionary_file.pkl'
    output:
        second = qc_dir + '/multiqc_report.html'
    params:
        computing_threads = config['computing_threads'],
        output_dir = config['output_dir']
    log:
        log_dir + '/fastq_download_and_qc.log'
    conda:
        conda_env_dir + '/fastq_download_and_qc.yaml' 
    script:
        'scripts/fastq_download_and_qc.py'
